<?php
session_start();
require_once __DIR__ . '/../includes/DB_Connect.php';
require_once __DIR__ . '/../includes/Activity_Log.php';
$role = strtolower($_SESSION['role'] ?? '');
if (!isset($_SESSION['user_id']) || !in_array($role, ['admin', 'manager', 'finance', 'hr', 'hr_admin'], true)) { header('Location: ../auth/Login_Page.php'); exit; }
if ($conn) ensure_activity_log($conn);
$audience = match ($role) { 'manager' => 'store_manager', 'finance' => 'finance', 'hr', 'hr_admin' => 'hr', default => 'admin' };
$rows = [];
if ($conn) { $stmt = mysqli_prepare($conn, 'SELECT * FROM activity_log WHERE FIND_IN_SET(?, audience) ORDER BY created_at DESC LIMIT 250'); mysqli_stmt_bind_param($stmt, 's', $audience); mysqli_stmt_execute($stmt); $res = mysqli_stmt_get_result($stmt); while ($res && ($row = mysqli_fetch_assoc($res))) $rows[] = $row; mysqli_stmt_close($stmt); }
$title = match ($role) { 'manager' => 'Inventory Activity History', 'finance' => 'Financial Activity History', 'hr', 'hr_admin' => 'Employee Activity History', default => 'Activity History' };
$back = match ($role) { 'manager' => '../manager/Manager_Dashboard.php', 'finance' => '../finance/finance.php', 'hr', 'hr_admin' => '../HR/HR_Dashboard.php', default => 'Admin_Page.php' };
?><!doctype html><html lang="en"><head><script src="../js/tab_session_guard.js"></script><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= htmlspecialchars($title) ?></title><link rel="stylesheet" href="../css/admin_page.css"><style>body{background:#f6f8fb;font-family:Arial,sans-serif}.history{max-width:1200px;margin:0 auto;padding:34px}.history-head{display:flex;justify-content:space-between;align-items:center;gap:14px;margin-bottom:22px}.history h1{margin:0;color:#102b47;font-size:28px}.back{background:#3672a8;color:#fff;border-radius:8px;padding:10px 14px;text-decoration:none;font-weight:700}.card{background:#fff;border:1px solid #e2e8f0;border-radius:14px;overflow:auto}.table{width:100%;border-collapse:collapse;font-size:14px}.table th,.table td{padding:13px 15px;text-align:left;border-bottom:1px solid #edf2f7}.table th{font-size:11px;color:#64748b;text-transform:uppercase}.badge{display:inline-block;border-radius:999px;padding:4px 8px;background:#f4e3d3;color:#225d93;font-size:12px;font-weight:700}.empty{padding:36px;text-align:center;color:#64748b}@media(max-width:650px){.history{padding:18px}.history-head{align-items:flex-start;flex-direction:column}.table{min-width:720px}}</style></head><body><main class="history"><div class="history-head"><div><h1><?= htmlspecialchars($title) ?></h1><p>Recent updates, additions, approvals, and archive actions assigned to your role.</p></div><a class="back" href="<?= htmlspecialchars($back) ?>">← Back to dashboard</a></div><section class="card"><?php if (!$rows): ?><div class="empty">No activity has been recorded for this role yet.</div><?php else: ?><table class="table"><thead><tr><th>When</th><th>Action</th><th>Record</th><th>Details</th><th>By</th></tr></thead><tbody><?php foreach ($rows as $row): ?><tr><td><?= htmlspecialchars(date('M d, Y g:i A', strtotime($row['created_at']))) ?></td><td><span class="badge"><?= htmlspecialchars(ucfirst($row['action'])) ?></span></td><td><?= htmlspecialchars(ucwords(str_replace('_', ' ', $row['target_type']))) ?><?= $row['target_id'] ? ' #' . htmlspecialchars($row['target_id']) : '' ?></td><td><?= htmlspecialchars($row['details'] ?: '—') ?></td><td><?= htmlspecialchars($row['actor_name'] ?: 'System') ?></td></tr><?php endforeach; ?></tbody></table><?php endif; ?></section></main></body></html>
